.travis.yml, README.rst, docs/examples.rst, pysnow.py, setup.py, test/incident.py
- Pypi config dependency fixes
- Tests (API mocking)
- Travis-ci
- Documentation updates
No API breakage
=> Version 0.2

README.rst, pysnow.py, tests/example.txt, tests/test_incident.py
Added new public method in Request class that will upload attachments to a record in a table
Updated README with an example
Update tests with an upload attachment test
=> add ability to upload attachment to a queried record

README.rst, docs/examples.rst, pysnow.py, tests/test_incident.py
Response error details with tests and documentation
Fixes #12
=> Response error details

README.rst, docs/client.rst, docs/query.rst, pysnow.py, tests/test_query.py
New version, features query builder and improved error handling
=> Branch0.3.0

pysnow.py, tests/test_incident.py
Added `limit` support in get_all()
=> Request limit

README.rst, pysnow.py, tests/test_incident.py
Adds `limit` support in get_all()
Enables easy access to last response (and request)
=> Branch0.3.2

pysnow.py, tests/test_incident.py, tests/test_query.py
=> Branch0.3.3

README.rst, docs/usage/client.rst, docs/usage/index.rst, docs/usage/query.rst, pysnow/__init__.py
=> Version 0.4.1

README.rst, docs/index.rst, docs/request.rst, docs/usage/full/clone.rst, docs/usage/full/create.rst, docs/usage/full/delete.rst, docs/usage/full/get_all.rst, docs/usage/full/get_one.rst, docs/usage/full/query_builder.rst, docs/usage/full/update.rst, docs/usage/index.rst, docs/usage/query.rst, docs/usage/request.rst, pysnow/__init__.py, pysnow/client.py, pysnow/query.py
Documentation fixes
Pypi readme fixes
=> Version 0.4.2

docs/usage/client.rst, docs/usage/full/query_builder.rst, docs/usage/query.rst, pysnow/__init__.py, tests/test_query.py
- Documentation updates
- Reworked QB tests
=> Branch0.4.3

README.rst, docs/usage/client.rst, docs/usage/query.rst, pysnow/__init__.py, pysnow/client.py, pysnow/request.py, tests/test_client.py, tests/test_query.py, tests/test_request.py
Deprecated default_payload
Added request_params
Added request_params usage example
Added request_params tests
=> Branch0.4.4

docs/usage/client.rst, docs/usage/full/count.rst, pysnow/__init__.py, pysnow/request.py, tests/test_request.py
Implemented request count
Documentation fixes
=> Branch0.4.6

docs/usage/full/count.rst, docs/usage/full/get_multiple.rst, docs/usage/full/pagination.rst, docs/usage/index.rst, pysnow/__init__.py, pysnow/request.py, tests/test_request.py
Implements offset in get_multiple()
=> Branch0.4.7

pysnow/__init__.py, pysnow/client.py, pysnow/request.py, tests/test_client.py
* Implemented use_ssl, fixes #51
* base_url is now created in `Client`
* `base` renamed to `base_path`
=> URL builder fixes

pysnow/exceptions.py, pysnow/query.py, pysnow/request.py, tests/test_query.py, tests/test_request.py
Fixes #53
Minor error handling fixes
=> Branch 0.4.10

pysnow/__init__.py, pysnow/query.py, tests/test_query.py
=> Branch 0.4.11

README.rst, pysnow/__init__.py, pysnow/client.py, setup.py
- Added missing oauth depdencies in setup
- Removed unused imports in client
- Added license badge
=> Branch 0.5.1

pysnow/__init__.py, pysnow/exceptions.py, pysnow/oauth_client.py, tests/test_oauth_client.py
OAuthClient error handling fixes
=> Branch 0.5.2

docs/full_examples/attachments.rst, docs/full_examples/fetch.rst, docs/index.rst, pysnow/__init__.py, pysnow/request.py, pysnow/resource.py, tests/test_resource.py
- Upped default chunk size
- Always look for QS params
- Attachment usage example
=> Branch 0.6.6

pysnow/legacy_request.py, pysnow/params_builder.py, pysnow/query_builder.py, pysnow/url_builder.py, tests/test_client.py
Most of my code imports unicode_literals.  This adds detection and a test.
It should quietly work just like before on python3.
=> Stub in basic unicode support for folks that use import unicode_literals

docs/full_examples/threads.rst, docs/index.rst
Add quick primer on using this with threads.
=> Add simple example for a threaded query

docs/api/exceptions.rst, docs/index.rst
Just a simple list of the defined exceptions
=> Add doc for exceptions

docs/api/attachment.rst, docs/full_examples/attachments.rst, docs/index.rst, pysnow/__init__.py, pysnow/attachment.py, pysnow/client.py, pysnow/oauth_client.py, pysnow/resource.py, tests/test_attachment.py, tests/test_oauth_client.py, tests/test_query_builder.py, tests/test_resource.py
- Adds the Attachment API
- Documentation updates
- Minor OAuth token fixes
=> Branch 0.7.0

pysnow/__init__.py, pysnow/resource.py
Fixes issue with cloning of Resource parameters
=> Branch 0.7.1

README.rst, docs/full_examples/fetch.rst, docs/full_examples/oauth_client.rst, pysnow/query_builder.py, pysnow/request.py, pysnow/resource.py, tests/test_query_builder.py
- Reworked argument handling in get()
- OAuth example, stream parser (#98)
- Added contributor and new project
=> Branch 0.7.5

docs/full_examples/filtering.rst, docs/index.rst
=> Add field filter usage example

docs/_themes/sphinx_rtd_theme/__init__.py, docs/conf.py, pysnow/__init__.py, pysnow/attachment.py, pysnow/client.py, pysnow/exceptions.py, pysnow/legacy_exceptions.py, pysnow/legacy_request.py, pysnow/oauth_client.py, pysnow/params_builder.py, pysnow/query_builder.py, pysnow/request.py, pysnow/resource.py, pysnow/response.py, pysnow/url_builder.py, tests/legacy/test_request.py, tests/test_attachment.py, tests/test_client.py, tests/test_oauth_client.py, tests/test_params_builder.py, tests/test_query_builder.py, tests/test_resource.py
=> Use Black formatter

pyproject.toml
Support python >= 27 and >= py35
=> Fix python requirements

pysnow/exceptions.py
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Add missing UnexpectedResponseFormat for backward compatability

pyproject.toml, pysnow/query_builder.py, tests/test_query_builder.py
=> Revert "Use GlideSystem for datetime comparison operations"

pysnow/resource.py
=> Fix deprecation warnings due to invalid escape sequences.

pysnow/request.py
=> typo in request.py
